import { StyleSheet, Dimensions } from 'react-native';

/**
 * BottomSlider styles are separated from BottomSlider.tsx to keep UI logic and styling modular.
 * This helps maintain consistency as the app grows (more screens/components).
 */

const SCREEN_WIDTH = Dimensions.get('window').width;

export const directionDetailsStyles = StyleSheet.create({
  contentScroll: {
    flex: 1,
    width: '100%',
  },
  contentScrollContent: {
    flexGrow: 1,
    paddingHorizontal: 16,
    paddingBottom: 96,
  },
  directionTitle: {
    maxWidth: SCREEN_WIDTH * 0.55,
    fontSize: 30,
    fontFamily: 'gabarito',
    fontWeight: '600',
    color: '#D8D8D8',
  },
  header: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'flex-start',
    marginBottom: 16,
    marginTop: 15,
  },
  locationHeader: {
    paddingRight: 10,
    paddingLeft: 5,
    borderRadius: 30,
    backgroundColor: 'rgba(0, 0, 0, 0.2)',
    boxShadow: 'inset 0 -3.5px 4px rgba(0, 0, 0, 0.4)',
  },
  subLocationHeader: {
    flexDirection: 'row',
    marginBottom: 0,
    marginTop: 0,
    marginLeft: 5,
    gap: 10,
    justifyContent: 'space-between',
  },
  inlineHeader: {
    flexDirection: 'row',
    marginBottom: 0,
    marginTop: 0,
    marginLeft: 5,
    alignSelf: 'flex-start',
    justifyContent: 'space-between',
  },
  separationHeader: {
    marginTop: -25,
    marginBottom: -25,
    flexDirection: 'row',
    marginLeft: 5,
    gap: 10,
    alignSelf: 'flex-start',
    justifyContent: 'space-between',
  },
  transportationSubHeader: {
    flexDirection: 'row',
    alignSelf: 'center',
    alignItems: 'flex-start',
    gap: 20,
  },
  transportationHeader: {
    borderRadius: 40,
    marginTop: 9,
    backgroundColor: 'rgba(0, 0, 0, 0.2)',
    boxShadow: 'inset 0 -3.5px 4px rgba(0, 0, 0, 0.4)',
  },
  transportationIcon: {
    color: '#fff',
    backgroundColor: 'transparent',
    alignSelf: 'center',
    padding: 10,
  },
  transportationButton: {
    flex: 1,
    backgroundColor: 'transparent',
    borderRadius: 40,
  },
  activeTransportationButton: {
    backgroundColor: 'rgba(0, 0, 0, 0.4)',
  },
  headerIcons: {
    flexDirection: 'row',
    gap: 10,
  },
  transitHeaderTextWrap: {
    flex: 1,
    paddingRight: 12,
  },
  transitHeaderTitleText: {
    color: '#FFFFFF',
  },
  shuttleScheduleHeaderTitle: {
    fontSize: 22,
    lineHeight: 28,
    fontWeight: '700',
    maxWidth: SCREEN_WIDTH * 0.6,
  },
  transitDestinationText: {
    color: '#FFFFFF',
    fontSize: 15,
    lineHeight: 20,
    fontFamily: 'gabarito',
    marginTop: 2,
  },
  crossCampusContainer: {
    alignSelf: 'center',
    paddingVertical: 2,
    paddingHorizontal: 8,
    borderRadius: 10,
    backgroundColor: 'rgba(4, 114, 248, 0.22)',
    borderWidth: 1,
    borderColor: 'rgba(4, 114, 248, 0.7)',
  },
  crossCampusText: {
    color: '#CFE4FF',
    fontSize: 11,
    fontFamily: 'gabarito',
    fontWeight: '700',
    letterSpacing: 0.2,
  },
  iconButton: {
    backgroundColor: 'rgba(0, 0, 0, 0.30)',
    borderWidth: 0.3,
    borderColor: 'rgba(255, 255, 255, 0.7)',
    borderRadius: 20,
    padding: 8,
    elevation: 10,
    boxShadow: 'inset 0 -3.5px 4px rgba(0, 0, 0, 0.4)',
  },
  locationButton: {
    backgroundColor: 'transparent',
    padding: 5.5,
    width: SCREEN_WIDTH * 0.5,
  },
  frontIcon: {
    color: '#fff',
    backgroundColor: 'transparent',
    padding: 8,
  },
  dragIcon: {
    color: '#fff',
    backgroundColor: 'transparent',
    padding: 8,
  },
  shuttleCardMetaContainer: {
    marginTop: 10,
    marginBottom: 0,
    paddingHorizontal: 2,
  },
  shuttleCardContainer: {
    paddingVertical: 12,
    paddingHorizontal: 16,
    borderRadius: 20,
    backgroundColor: 'rgba(39, 21, 21, 0.82)',
    borderWidth: 1,
    borderColor: 'rgba(255, 255, 255, 0.08)',
    boxShadow: '0 10px 18px rgba(0, 0, 0, 0.32)',
  },
  shuttleDirectionText: {
    color: '#AAB3C0',
    fontSize: 14,
    lineHeight: 18,
    fontFamily: 'gabarito',
    fontWeight: '600',
    letterSpacing: 0.2,
  },
  shuttleCardTopRow: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    gap: 10,
  },
  shuttleHeaderSpacer: {
    flex: 1,
  },
  shuttleScheduleButton: {
    width: 40,
    height: 40,
    borderRadius: 12,
    backgroundColor: 'rgba(255, 255, 255, 0.06)',
    borderWidth: 0,
    alignItems: 'center',
    justifyContent: 'center',
    marginRight: 4,
  },
  shuttleScheduleIcon: {
    width: 24,
    gap: 4,
  },
  shuttleScheduleIconRow: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 4,
  },
  shuttleScheduleDot: {
    width: 4,
    height: 4,
    borderRadius: 2,
    color: '#FFFFFF',
    backgroundColor: '#FFFFFF',
  },
  shuttleScheduleLine: {
    flex: 1,
    height: 3,
    borderRadius: 2,
    backgroundColor: '#FFFFFF',
  },
  shuttleScheduleButtonText: {
    color: '#B7D8FF',
    fontSize: 12,
    lineHeight: 15,
    fontFamily: 'gabarito',
    fontWeight: '700',
    letterSpacing: 0.15,
  },
  shuttlePrimaryText: {
    flex: 1,
    marginTop: 0,
    color: '#FFFFFF',
    fontSize: 20,
    lineHeight: 28,
    fontFamily: 'gabarito',
    fontWeight: '700',
  },
  shuttleSecondaryText: {
    marginTop: 3,
    color: '#D1D6DE',
    fontSize: 14,
    lineHeight: 19,
    fontFamily: 'gabarito',
    fontWeight: '500',
  },
  shuttleUnavailableCard: {
    marginTop: 0,
    paddingVertical: 10,
    paddingHorizontal: 10,
    borderRadius: 12,
    backgroundColor: 'rgba(184, 138, 0, 0.12)',
    borderWidth: 1,
    borderColor: 'rgba(244, 193, 91, 0.35)',
  },
  shuttleUnavailableRow: {
    flexDirection: 'row',
    alignItems: 'flex-start',
    gap: 10,
  },
  shuttleUnavailableIconWrap: {
    width: 28,
    height: 28,
    borderRadius: 14,
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: 'rgba(244, 193, 91, 0.18)',
  },
  shuttleUnavailableTextWrap: {
    flex: 1,
  },
  shuttleUnavailableButtonWrap: {
    alignSelf: 'flex-start',
  },
  shuttleUnavailableTitle: {
    color: '#FFD98A',
    fontSize: 15,
    lineHeight: 19,
    fontFamily: 'gabarito',
    fontWeight: '700',
  },
  shuttleUnavailableText: {
    marginTop: 2,
    color: '#F2D59A',
    fontSize: 14,
    lineHeight: 20,
    fontFamily: 'gabarito',
    fontWeight: '600',
  },
  shuttleScheduleDetailsCard: {
    marginTop: 4,
    marginBottom: 10,
    paddingVertical: 12,
    paddingHorizontal: 16,
    borderRadius: 20,
    backgroundColor: 'rgba(39, 21, 21, 0.82)',
    borderWidth: 1,
    borderColor: 'rgba(255, 255, 255, 0.08)',
    boxShadow: '0 10px 18px rgba(0, 0, 0, 0.32)',
  },
  shuttleScheduleContainer: {
    marginTop: 10,
    paddingTop: 10,
    borderTopWidth: 1,
    borderTopColor: 'rgba(255, 255, 255, 0.1)',
    gap: 10,
  },
  shuttleScheduleFullContent: {
    marginTop: 4,
    marginBottom: 28,
    gap: 10,
  },
  shuttleScheduleDayCard: {
    paddingVertical: 10,
    paddingHorizontal: 10,
    borderRadius: 12,
    backgroundColor: 'rgba(255, 255, 255, 0.04)',
    borderWidth: 1,
    borderColor: 'rgba(255, 255, 255, 0.06)',
  },
  shuttleScheduleTitle: {
    color: '#FFFFFF',
    fontSize: 15,
    lineHeight: 19,
    fontFamily: 'gabarito',
    fontWeight: '800',
  },
  shuttleScheduleTimesWrap: {
    marginTop: 8,
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: 8,
  },
  shuttleScheduleTimeChip: {
    paddingVertical: 5,
    paddingHorizontal: 8,
    borderRadius: 8,
    backgroundColor: 'rgba(8, 57, 79, 0.4)',
    borderWidth: 1,
    borderColor: 'rgba(120, 202, 255, 0.25)',
  },
  shuttleScheduleTimeChipHighlighted: {
    backgroundColor: 'rgba(38, 161, 255, 0.28)',
    borderColor: 'rgba(78, 197, 255, 0.85)',
  },
  shuttleScheduleTimeText: {
    color: '#D8ECFF',
    fontSize: 13,
    lineHeight: 16,
    fontFamily: 'gabarito',
    fontWeight: '600',
  },
  shuttleScheduleTimeTextHighlighted: {
    color: '#FFFFFF',
    fontWeight: '800',
  },
  routeMetaContainer: {
    marginTop: 10,
    marginBottom: 10,
    paddingVertical: 16,
    paddingHorizontal: 16,
    borderRadius: 26,
    backgroundColor: 'rgba(39, 21, 21, 0.82)',
    borderWidth: 1,
    borderColor: 'rgba(255, 255, 255, 0.08)',
    minHeight: 126,
    justifyContent: 'center',
    boxShadow: '0 10px 18px rgba(0, 0, 0, 0.32)',
  },
  routeMetaText: {
    color: '#D8D8D8',
    fontSize: 16,
    fontFamily: 'gabarito',
  },
  routeErrorText: {
    color: '#FF8C8C',
    fontSize: 16,
    fontFamily: 'gabarito',
  },
  routeRetryButton: {
    marginTop: 10,
    alignSelf: 'flex-start',
    borderRadius: 14,
    paddingVertical: 8,
    paddingHorizontal: 14,
    backgroundColor: 'rgba(255, 255, 255, 0.12)',
    borderWidth: 1,
    borderColor: 'rgba(255, 255, 255, 0.18)',
  },
  routeRetryButtonText: {
    color: '#FFFFFF',
    fontSize: 14,
    lineHeight: 17,
    fontFamily: 'gabarito',
    fontWeight: '700',
  },
  routeSummaryRow: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    gap: 10,
  },
  routeSummaryTextWrap: {
    flex: 1,
    paddingRight: 12,
  },
  routeSecondaryInlineRow: {
    marginTop: 2,
    flexDirection: 'row',
    alignItems: 'center',
    flexWrap: 'nowrap',
    gap: 6,
  },
  routeSecondaryDot: {
    color: '#AEB1B7',
    fontSize: 14,
    fontFamily: 'gabarito',
    lineHeight: 16,
  },
  routePrimaryText: {
    color: '#FFFFFF',
    fontSize: 31,
    lineHeight: 38,
    fontFamily: 'gabarito',
    fontWeight: '700',
    flexShrink: 1,
    minWidth: 0,
  },
  routeSecondaryText: {
    marginTop: 0,
    color: '#AEB1B7',
    fontSize: 17,
    lineHeight: 20,
    fontFamily: 'gabarito',
    fontWeight: '500',
    flexShrink: 1,
    minWidth: 0,
  },
  routeGoButton: {
    width: 80,
    height: 80,
    borderRadius: 25,
    backgroundColor: '#32D35A',
    alignItems: 'center',
    justifyContent: 'center',
    boxShadow: '0 8px 12px rgba(0, 0, 0, 0.25)',
  },
  routeGoButtonDisabled: {
    opacity: 0.4,
  },
  routeGoText: {
    color: '#FFFFFF',
    fontSize: 37,
    lineHeight: 46,
    fontFamily: 'gabarito',
    fontWeight: '700',
    letterSpacing: 0.8,
  },
  navigationSummaryCard: {
    marginTop: 8,
    marginBottom: 8,
    paddingVertical: 14,
    paddingHorizontal: 10,
    borderRadius: 50,
    backgroundColor: 'rgba(39, 21, 21, 0.82)',
    borderWidth: 1,
    borderColor: 'rgba(255, 255, 255, 0.08)',
    boxShadow: '0 10px 18px rgba(0, 0, 0, 0.32)',
  },
  navigationSummaryRow: {
    flexDirection: 'row',
    alignItems: 'stretch',
    justifyContent: 'space-between',
  },
  navigationSummaryStat: {
    flex: 1,
    alignItems: 'center',
    justifyContent: 'center',
    paddingVertical: 6,
    minWidth: 0,
  },
  navigationSummaryValue: {
    color: '#FFFFFF',
    fontSize: 32,
    lineHeight: 36,
    fontFamily: 'gabarito',
    fontWeight: '700',
  },
  navigationSummaryLabel: {
    marginTop: 4,
    color: '#AEB1B7',
    fontSize: 16,
    lineHeight: 20,
    fontFamily: 'gabarito',
    fontWeight: '500',
  },
  navigationSummaryDivider: {
    width: 1,
    marginVertical: 8,
    marginHorizontal: 9,
    backgroundColor: 'rgba(255, 255, 255, 0.08)',
  },
  navigationEndButton: {
    alignSelf: 'center',
    marginTop: 4,
    marginBottom: 8,
    width: '86%',
    maxWidth: 420,
    minWidth: 260,
    paddingVertical: 13,
    paddingHorizontal: 28,
    borderRadius: 999,
    backgroundColor: 'rgba(182, 45, 45, 0.94)',
    borderWidth: 1,
    borderColor: 'rgba(255, 255, 255, 0.14)',
    boxShadow: '0 8px 14px rgba(0, 0, 0, 0.28)',
  },
  navigationEndButtonText: {
    color: '#FFFFFF',
    textAlign: 'center',
    fontSize: 17,
    lineHeight: 22,
    fontFamily: 'gabarito',
    fontWeight: '700',
    letterSpacing: 0.2,
  },
  transitContainer: {
    marginTop: 2,
    marginBottom: 24,
    paddingTop: 10,
    paddingBottom: 4,
    borderRadius: 24,
    backgroundColor: 'rgba(20, 22, 27, 0.92)',
    borderWidth: 1,
    borderColor: 'rgba(255, 255, 255, 0.08)',
    boxShadow: '0 10px 18px rgba(0, 0, 0, 0.32)',
  },
  transitTitle: {
    color: '#FFFFFF',
    fontSize: 20,
    fontFamily: 'gabarito',
    fontWeight: '700',
    marginHorizontal: 16,
    marginBottom: 6,
  },
  transitEmptyText: {
    color: '#B5BBC4',
    fontSize: 15,
    lineHeight: 21,
    fontFamily: 'gabarito',
    marginHorizontal: 16,
    marginBottom: 12,
  },
  transitStepRow: {
    flexDirection: 'row',
    alignItems: 'flex-start',
    gap: 12,
    paddingHorizontal: 16,
    paddingVertical: 13,
  },
  transitStepRowWithDivider: {
    borderTopWidth: 1,
    borderTopColor: 'rgba(255, 255, 255, 0.08)',
  },
  transitLineBadge: {
    minWidth: 36,
    height: 36,
    borderRadius: 7,
    alignItems: 'center',
    justifyContent: 'center',
    paddingHorizontal: 6,
  },
  transitLineBadgeText: {
    fontSize: 18,
    lineHeight: 20,
    fontFamily: 'gabarito',
    fontWeight: '700',
  },
  transitIconBadge: {
    width: 36,
    height: 36,
    borderRadius: 18,
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: '#4E5968',
  },
  transitStepBody: {
    flex: 1,
  },
  transitStepTitle: {
    color: '#F4F6FA',
    fontSize: 28,
    lineHeight: 34,
    fontFamily: 'gabarito',
    fontWeight: '700',
  },
  transitStepSubtitle: {
    color: '#B8C0CB',
    fontSize: 14,
    lineHeight: 19,
    fontFamily: 'gabarito',
    marginTop: 2,
  },
  transitStepDetail: {
    color: '#2DA1FF',
    fontSize: 15,
    lineHeight: 20,
    fontFamily: 'gabarito',
    marginTop: 4,
  },
  transitStepStopText: {
    color: '#D4D8DE',
    fontSize: 14,
    lineHeight: 18,
    fontFamily: 'gabarito',
    marginTop: 4,
  },
  transitTimeRow: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: 10,
    marginTop: 6,
  },
  transitStepTimeText: {
    color: '#E5E8EE',
    fontSize: 14,
    lineHeight: 18,
    fontFamily: 'gabarito',
    fontWeight: '600',
  },
});
