import { StyleSheet, Dimensions } from 'react-native';

/**
 * BottomSlider styles are separated from BottomSlider.tsx to keep UI logic and styling modular.
 * This helps maintain consistency as the app grows (more screens/components).
 */

const SCREEN_WIDTH = Dimensions.get('window').width;

export const directionDetailsStyles = StyleSheet.create({
  directionTitle: {
    maxWidth: SCREEN_WIDTH * 0.55,
    fontSize: 30,
    fontFamily: 'gabarito',
    fontWeight: '600',
    color: '#D8D8D8',
  },
  header: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'flex-start',
    marginBottom: 16,
    marginTop: 15,
  },
  locationHeader: {
    paddingRight: 10,
    paddingLeft: 5,
    borderRadius: 30,
    backgroundColor: 'rgba(0, 0, 0, 0.2)',
    boxShadow: 'inset 0 -3.5px 4px rgba(0, 0, 0, 0.4)',
  },
  subLocationHeader: {
    flexDirection: 'row',
    marginBottom: 0,
    marginTop: 0,
    marginLeft: 5,
    gap: 10,
    justifyContent: 'space-between',
  },
  inlineHeader: {
    flexDirection: 'row',
    marginBottom: 0,
    marginTop: 0,
    marginLeft: 5,
    alignSelf: 'flex-start',
    justifyContent: 'space-between',
  },
  separationHeader: {
    marginTop: -25,
    marginBottom: -25,
    flexDirection: 'row',
    marginLeft: 5,
    gap: 10,
    alignSelf: 'flex-start',
    justifyContent: 'space-between',
  },
  transportationSubHeader: {
    flexDirection: 'row',
    alignSelf: 'center',
    alignItems: 'flex-start',
    gap: 20,
  },
  transportationHeader: {
    borderRadius: 40,
    marginTop: 9,
    backgroundColor: 'rgba(0, 0, 0, 0.2)',
    boxShadow: 'inset 0 -3.5px 4px rgba(0, 0, 0, 0.4)',
  },
  transportationIcon: {
    color: '#fff',
    backgroundColor: 'transparent',
    alignSelf: 'center',
    padding: 10,
  },
  transportationButton: {
    flex: 1,
    backgroundColor: 'transparent',
    borderRadius: 40,
  },
  activeTransportationButton: {
    backgroundColor: 'rgba(0, 0, 0, 0.4)',
  },
  headerIcons: {
    flexDirection: 'row',
    gap: 10,
  },
  crossCampusContainer: {
    alignSelf: 'center',
    paddingVertical: 2,
    paddingHorizontal: 8,
    borderRadius: 10,
    backgroundColor: 'rgba(4, 114, 248, 0.22)',
    borderWidth: 1,
    borderColor: 'rgba(4, 114, 248, 0.7)',
  },
  crossCampusText: {
    color: '#CFE4FF',
    fontSize: 11,
    fontFamily: 'gabarito',
    fontWeight: '700',
    letterSpacing: 0.2,
  },
  iconButton: {
    backgroundColor: 'rgba(0, 0, 0, 0.30)',
    borderWidth: 0.3,
    borderColor: 'rgba(255, 255, 255, 0.7)',
    borderRadius: 20,
    padding: 8,
    elevation: 10,
    boxShadow: 'inset 0 -3.5px 4px rgba(0, 0, 0, 0.4)',
  },
  locationButton: {
    backgroundColor: 'transparent',
    padding: 5.5,
    width: SCREEN_WIDTH * 0.5,
  },
  frontIcon: {
    color: '#fff',
    backgroundColor: 'transparent',
    padding: 8,
  },
  dragIcon: {
    color: '#fff',
    backgroundColor: 'transparent',
    padding: 8,
  },
  routeMetaContainer: {
    marginTop: 10,
    marginBottom: 10,
    paddingVertical: 16,
    paddingHorizontal: 16,
    borderRadius: 26,
    backgroundColor: 'rgba(39, 21, 21, 0.82)',
    borderWidth: 1,
    borderColor: 'rgba(255, 255, 255, 0.08)',
    minHeight: 126,
    justifyContent: 'center',
    boxShadow: '0 10px 18px rgba(0, 0, 0, 0.32)',
  },
  routeMetaText: {
    color: '#D8D8D8',
    fontSize: 16,
    fontFamily: 'gabarito',
  },
  routeErrorText: {
    color: '#FF8C8C',
    fontSize: 16,
    fontFamily: 'gabarito',
  },
  routeSummaryRow: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    gap: 10,
  },
  routeSummaryTextWrap: {
    flex: 1,
    paddingRight: 12,
  },
  routeSecondaryInlineRow: {
    marginTop: 2,
    flexDirection: 'row',
    alignItems: 'center',
    flexWrap: 'nowrap',
    gap: 6,
  },
  routeSecondaryDot: {
    color: '#AEB1B7',
    fontSize: 14,
    fontFamily: 'gabarito',
    lineHeight: 16,
  },
  routePrimaryText: {
    color: '#FFFFFF',
    fontSize: 37,
    lineHeight: 58,
    fontFamily: 'gabarito',
    fontWeight: '700',
  },
  routeSecondaryText: {
    marginTop: 0,
    color: '#AEB1B7',
    fontSize: 17,
    lineHeight: 20,
    fontFamily: 'gabarito',
    fontWeight: '500',
    flexShrink: 1,
    minWidth: 0,
  },
  routeGoButton: {
    width: 80,
    height: 80,
    borderRadius: 25,
    backgroundColor: '#32D35A',
    alignItems: 'center',
    justifyContent: 'center',
    boxShadow: '0 8px 12px rgba(0, 0, 0, 0.25)',
  },
  routeGoText: {
    color: '#FFFFFF',
    fontSize: 37,
    lineHeight: 46,
    fontFamily: 'gabarito',
    fontWeight: '700',
    letterSpacing: 0.8,
  },
});
