import { StyleSheet } from 'react-native';

export default StyleSheet.create({
    container: {
        ...StyleSheet.absoluteFillObject,
        backgroundColor: 'white',
    },
    pathBar: {
        position: 'absolute',
        bottom: 160,
        left: 16,
        right: 16,
        zIndex: 100,
        elevation: 10,
        flexDirection: 'row',
        alignItems: 'center',
        gap: 8,
        backgroundColor: 'white',
        borderRadius: 12,
        padding: 10,
        shadowColor: '#000',
        shadowOffset: { width: 0, height: 2 },
        shadowOpacity: 0.15,
        shadowRadius: 6,
    },
    pathBtn: {
        flex: 1,
        backgroundColor: '#eee',
        borderRadius: 8,
        paddingVertical: 8,
        paddingHorizontal: 10,
    },
    pathBtnActive: {
        backgroundColor: '#ddeeff',
        borderWidth: 1,
        borderColor: '#0057FF',
    },
    pathBtnText: { fontSize: 13, color: '#333' },
    clearBtn: {
        backgroundColor: '#ffdddd',
        borderRadius: 8,
        padding: 8,
    },
    clearBtnText: { color: '#FF4444', fontSize: 14, fontWeight: '600' },
    pathSteps: {
        position: 'absolute',
        bottom: 210,
        right: 16,
        zIndex: 100,
        elevation: 10,
        backgroundColor: 'rgba(255,255,255,0.95)',
        borderRadius: 12,
        padding: 8,
        width: 175,
        shadowColor: '#000',
        shadowOffset: { width: 0, height: 2 },
        shadowOpacity: 0.15,
        shadowRadius: 6,
        gap: 4,
        opacity: 0.7,
    },
    stepRow: {
        flexDirection: 'row',
        alignItems: 'center',
        gap: 4,
    },
    stepIcon: { fontSize: 11 },
    stepText: { fontSize: 11, color: '#333', flexShrink: 1 },
    pathNavBar: {
        position: 'absolute',
        bottom: 120,
        left: 16,
        right: 16,
        zIndex: 100,
        elevation: 10,
        flexDirection: 'row',
        borderRadius: 12,
        overflow: 'hidden',
        shadowColor: '#000',
        shadowOffset: { width: 0, height: 2 },
        shadowOpacity: 0.15,
        shadowRadius: 6,
    },
    pathNavBtn: {
        flex: 1,
        backgroundColor: '#922338',
        paddingVertical: 10,
        alignItems: 'center',
    },
    pathNavDivider: {
        width: 1,
        backgroundColor: '#ffffff40',
    },
    pathNavText: {
        color: '#fff',
        fontWeight: '700',
        fontSize: 13,
    },
    pathFloorNav: {
        position: 'absolute',
        bottom: 170,
        alignSelf: 'center',
        flexDirection: 'row',
        alignItems: 'center',
        gap: 12,
        backgroundColor: 'rgba(146, 35, 56, 0.9)',
        borderRadius: 20,
        paddingVertical: 8,
        paddingHorizontal: 16,
        zIndex: 100,
        elevation: 10,
    },
    pathFloorBtn: {
        padding: 4,
    },
    pathFloorText: {
        color: '#fff',
        fontSize: 13,
        fontWeight: '700',
    },
    pathFloorCurrent: {
        color: '#fff',
        fontSize: 13,
        fontWeight: '600',
    },
    reopenNavButton: {
        position: 'absolute',
        bottom: 30,
        alignSelf: 'center',
        backgroundColor: 'rgba(146, 35, 56, 0.9)',
        borderRadius: 20,
        paddingVertical: 10,
        paddingHorizontal: 20,
        zIndex: 100,
        elevation: 10,
    },
    reopenNavText: {
        color: '#fff',
        fontWeight: '700',
        fontSize: 14,
        fontFamily: 'gabarito',
    },
});