import { StyleSheet } from 'react-native';

export const upcomingClassesSliderStyles = StyleSheet.create({
  container: {
    flex: 1,
    paddingHorizontal: 8,
  },
  headerRow: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    marginBottom: 12,
    paddingHorizontal: 2,
    gap: 10,
  },
  headerDateTimeText: {
    color: '#ffffff',
    fontSize: 22,
    fontWeight: '700',
    flex: 1,
  },
  headerCloseButton: {
    width: 32,
    height: 32,
    borderRadius: 16,
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: 'rgba(0, 0, 0, 0.18)',
  },
  card: {
    backgroundColor: 'rgba(99, 24, 39, 0.72)',
    borderRadius: 18,
    borderWidth: 1,
    borderColor: 'rgba(255,255,255,0.1)',
    paddingHorizontal: 12,
    paddingTop: 12,
    paddingBottom: 36,
    gap: 10,
    alignSelf: 'stretch',
  },
  title: {
    color: '#ffffff',
    fontSize: 14,
    fontWeight: '700',
  },
  nextClassSummaryCard: {
    backgroundColor: 'rgba(25, 8, 12, 0.72)',
    borderRadius: 12,
    borderWidth: 1,
    borderColor: 'rgba(255,255,255,0.14)',
    paddingHorizontal: 11,
    paddingVertical: 10,
    marginBottom: 10,
    gap: 3,
  },
  nextClassSummaryCardUrgent: {
    borderColor: 'rgba(255, 165, 0, 0.7)',
    backgroundColor: 'rgba(87, 34, 8, 0.65)',
  },
  nextClassSummaryHeaderRow: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    gap: 8,
  },
  nextClassSummaryLabel: {
    color: '#FFFFFF',
    fontSize: 12,
    fontWeight: '800',
    letterSpacing: 0.3,
  },
  nextClassTitle: {
    color: '#FFFFFF',
    fontSize: 15,
    fontWeight: '700',
  },
  nextClassMeta: {
    color: 'rgba(255,255,255,0.86)',
    fontSize: 12,
    fontWeight: '500',
  },
  urgencyBadge: {
    borderRadius: 999,
    backgroundColor: 'rgba(255, 183, 0, 0.2)',
    borderWidth: 1,
    borderColor: 'rgba(255, 183, 0, 0.7)',
    paddingHorizontal: 8,
    paddingVertical: 3,
  },
  urgencyBadgeText: {
    color: '#FFD775',
    fontSize: 11,
    fontWeight: '700',
  },
  contentArea: {
    flex: 1,
    minHeight: 0,
  },
  routeGeneratingWrap: {
    marginBottom: 10,
    alignItems: 'center',
    gap: 6,
  },
  eventsViewport: {
    width: '100%',
    minHeight: 0,
    flexShrink: 1,
    overflow: 'hidden',
  },
  eventsList: {
    width: '100%',
    flexGrow: 0,
  },
  eventsContent: {
    gap: 8,
  },
  overflowIndicatorText: {
    color: '#ffffff',
    fontSize: 22,
    fontWeight: '700',
    textAlign: 'center',
    letterSpacing: 4,
  },
  eventItem: {
    backgroundColor: 'rgba(45, 10, 16, 0.65)',
    borderWidth: 1,
    borderColor: 'rgba(255,255,255,0.12)',
    borderRadius: 14,
    height: 68,
    paddingHorizontal: 12,
    paddingVertical: 8,
    flexDirection: 'row',
    alignItems: 'center',
    gap: 10,
  },
  eventTextWrap: {
    flex: 1,
    gap: 3,
  },
  eventTitleText: {
    color: '#ffffff',
    fontSize: 13,
    fontWeight: '700',
  },
  eventMetaText: {
    color: 'rgba(255,255,255,0.85)',
    fontSize: 12,
    fontWeight: '500',
  },
  infoText: {
    color: 'rgba(255,255,255,0.85)',
    fontSize: 13,
    textAlign: 'center',
  },
  errorText: {
    color: '#ffd8ab',
    fontSize: 13,
    textAlign: 'center',
  },
  actionErrorWrap: {
    gap: 8,
    marginBottom: 8,
  },
  retryButton: {
    alignSelf: 'center',
    backgroundColor: 'rgba(255,255,255,0.16)',
    borderRadius: 10,
    paddingHorizontal: 12,
    paddingVertical: 6,
  },
  retryButtonText: {
    color: '#ffffff',
    fontSize: 12,
    fontWeight: '700',
  },
  reselectButton: {
    alignSelf: 'stretch',
    marginTop: 12,
    backgroundColor: 'rgba(255,255,255,0.16)',
    borderRadius: 10,
    paddingVertical: 10,
    alignItems: 'center',
  },
  reselectButtonText: {
    color: '#ffffff',
    fontSize: 13,
    fontWeight: '700',
  },
});
