import type { OutdoorPoi } from '../types/Poi';

/**
 * Curated outdoor POIs stored locally for the school project.
 * This list is intentionally static for the school project.
 */
export const OUTDOOR_POIS: OutdoorPoi[] = [
  {
    id: 'cafe-sgw-01',
    name: 'Starbucks',
    category: 'cafe',
    campus: 'SGW',
    latitude: 45.4976,
    longitude: -73.5793,
    address: '1455 Boulevard de Maisonneuve O, Montreal, QC',
  },
  {
    id: 'cafe-sgw-02',
    name: 'Second Cup',
    category: 'cafe',
    campus: 'SGW',
    latitude: 45.4959,
    longitude: -73.5778,
    address: '1600 Saint-Catherine St W, Montreal, QC',
  },
  {
    id: 'cafe-sgw-03',
    name: 'Tim Hortons',
    category: 'cafe',
    campus: 'SGW',
    latitude: 45.4968,
    longitude: -73.5784,
    address: '1550 De Maisonneuve Blvd W, Montreal, QC',
  },
  {
    id: 'cafe-sgw-04',
    name: 'Cafe Myriade',
    category: 'cafe',
    campus: 'SGW',
    latitude: 45.4952,
    longitude: -73.5766,
    address: '1432 Mackay St, Montreal, QC',
  },
  {
    id: 'cafe-sgw-05',
    name: 'Java U',
    category: 'cafe',
    campus: 'SGW',
    latitude: 45.4948,
    longitude: -73.5772,
    address: '1455 Peel St, Montreal, QC',
  },
  {
    id: 'cafe-sgw-06',
    name: 'Cafe Saint-Henri',
    category: 'cafe',
    campus: 'SGW',
    latitude: 45.4955,
    longitude: -73.5821,
    address: '1812 Notre-Dame St W, Montreal, QC',
  },
  {
    id: 'cafe-sgw-07',
    name: 'Dispatch Coffee',
    category: 'cafe',
    campus: 'SGW',
    latitude: 45.4939,
    longitude: -73.5787,
    address: '267 Saint-Antoine St W, Montreal, QC',
  },
  {
    id: 'cafe-sgw-08',
    name: 'Tommy Cafe',
    category: 'cafe',
    campus: 'SGW',
    latitude: 45.5001,
    longitude: -73.5795,
    address: '151 Saint-Paul St W, Montreal, QC',
  },
  {
    id: 'cafe-sgw-09',
    name: 'Crew Collective Cafe',
    category: 'cafe',
    campus: 'SGW',
    latitude: 45.5007,
    longitude: -73.5616,
    address: '360 Saint-Jacques St, Montreal, QC',
  },
  {
    id: 'cafe-sgw-10',
    name: 'Cafe Olimpico Downtown',
    category: 'cafe',
    campus: 'SGW',
    latitude: 45.4972,
    longitude: -73.5752,
    address: '1242 Drummond St, Montreal, QC',
  },
  {
    id: 'cafe-sgw-11',
    name: 'N49P Espresso',
    category: 'cafe',
    campus: 'SGW',
    latitude: 45.4994,
    longitude: -73.5738,
    address: '49 Prince-Arthur St W, Montreal, QC',
  },
  {
    id: 'cafe-sgw-12',
    name: 'Cafe Humble Lion',
    category: 'cafe',
    campus: 'SGW',
    latitude: 45.4898,
    longitude: -73.5842,
    address: '904 Sherbrooke St W, Montreal, QC',
  },
  {
    id: 'cafe-sgw-13',
    name: 'McCafe',
    category: 'cafe',
    campus: 'SGW',
    latitude: 45.4979,
    longitude: -73.5761,
    address: '1500 Sainte-Catherine St W, Montreal, QC',
  },
  {
    id: 'cafe-sgw-14',
    name: 'Van Houtte',
    category: 'cafe',
    campus: 'SGW',
    latitude: 45.4946,
    longitude: -73.5761,
    address: '1250 Rene-Levesque Blvd W, Montreal, QC',
  },
  {
    id: 'cafe-sgw-15',
    name: 'Cafe Castel',
    category: 'cafe',
    campus: 'SGW',
    latitude: 45.4971,
    longitude: -73.5743,
    address: '1316 Sherbrooke St W, Montreal, QC',
  },
  {
    id: 'cafe-loy-01',
    name: 'Starbucks Monkland',
    category: 'cafe',
    campus: 'LOYOLA',
    latitude: 45.4618,
    longitude: -73.6392,
    address: '6450 Monkland Ave, Montreal, QC',
  },
  {
    id: 'cafe-loy-02',
    name: 'Second Cup NDG',
    category: 'cafe',
    campus: 'LOYOLA',
    latitude: 45.4599,
    longitude: -73.6411,
    address: '5500 Monkland Ave, Montreal, QC',
  },
  {
    id: 'cafe-loy-03',
    name: 'Tim Hortons Loyola',
    category: 'cafe',
    campus: 'LOYOLA',
    latitude: 45.4585,
    longitude: -73.6404,
    address: '7141 Sherbrooke St W, Montreal, QC',
  },
  {
    id: 'cafe-loy-04',
    name: 'Cafe de Mercanti',
    category: 'cafe',
    campus: 'LOYOLA',
    latitude: 45.4613,
    longitude: -73.6378,
    address: '6121 Sherbrooke St W, Montreal, QC',
  },
  {
    id: 'cafe-loy-05',
    name: 'Cafe 92 Degrees',
    category: 'cafe',
    campus: 'LOYOLA',
    latitude: 45.4591,
    longitude: -73.6432,
    address: '6700 Chemin de la Cote-Saint-Luc, Montreal, QC',
  },
  {
    id: 'cafe-loy-06',
    name: 'Saint-Henri Micro-Torrefaction NDG',
    category: 'cafe',
    campus: 'LOYOLA',
    latitude: 45.463,
    longitude: -73.6284,
    address: '6792 Rue Notre-Dame O, Montreal, QC',
  },
  {
    id: 'cafe-loy-07',
    name: 'Cafe Zezin',
    category: 'cafe',
    campus: 'LOYOLA',
    latitude: 45.4616,
    longitude: -73.6297,
    address: '6115 Sherbrooke St W, Montreal, QC',
  },
  {
    id: 'cafe-loy-08',
    name: 'Aunja Cafe West',
    category: 'cafe',
    campus: 'LOYOLA',
    latitude: 45.4565,
    longitude: -73.6482,
    address: '5200 Queen Mary Rd, Montreal, QC',
  },
  {
    id: 'cafe-loy-09',
    name: 'Cafe Gentile',
    category: 'cafe',
    campus: 'LOYOLA',
    latitude: 45.4598,
    longitude: -73.6471,
    address: '4126 Sainte-Catherine St W, Westmount, QC',
  },
  {
    id: 'cafe-loy-10',
    name: 'MELK Bar a Cafe',
    category: 'cafe',
    campus: 'LOYOLA',
    latitude: 45.4639,
    longitude: -73.6215,
    address: '5612 Monkland Ave, Montreal, QC',
  },
  {
    id: 'cafe-loy-11',
    name: 'Cafe Pista NDG',
    category: 'cafe',
    campus: 'LOYOLA',
    latitude: 45.4604,
    longitude: -73.6326,
    address: '5542 Sherbrooke St W, Montreal, QC',
  },
  {
    id: 'cafe-loy-12',
    name: 'Le Butterblume',
    category: 'cafe',
    campus: 'LOYOLA',
    latitude: 45.4648,
    longitude: -73.6248,
    address: '5836 Sherbrooke St W, Montreal, QC',
  },
  {
    id: 'cafe-loy-13',
    name: 'Cafe Cantina',
    category: 'cafe',
    campus: 'LOYOLA',
    latitude: 45.4575,
    longitude: -73.6364,
    address: '6900 Sherbrooke St W, Montreal, QC',
  },
  {
    id: 'cafe-loy-14',
    name: 'Brioche a Tete',
    category: 'cafe',
    campus: 'LOYOLA',
    latitude: 45.4627,
    longitude: -73.6269,
    address: '5440 Queen Mary Rd, Montreal, QC',
  },
  {
    id: 'cafe-loy-15',
    name: 'Cafe Lounge Sherbrooke',
    category: 'cafe',
    campus: 'LOYOLA',
    latitude: 45.4589,
    longitude: -73.6386,
    address: '6500 Sherbrooke St W, Montreal, QC',
  },
  {
    id: 'restaurant-sgw-01',
    name: 'Boustan',
    category: 'restaurant',
    campus: 'SGW',
    latitude: 45.4964,
    longitude: -73.5779,
    address: '2020 Crescent St, Montreal, QC',
  },
  {
    id: 'restaurant-sgw-02',
    name: 'Subway',
    category: 'restaurant',
    campus: 'SGW',
    latitude: 45.4969,
    longitude: -73.5781,
    address: '1455 De Maisonneuve Blvd W, Montreal, QC',
  },
  {
    id: 'restaurant-sgw-03',
    name: 'Poulet Rouge',
    category: 'restaurant',
    campus: 'SGW',
    latitude: 45.4974,
    longitude: -73.5766,
    address: '1616 Sainte-Catherine St W, Montreal, QC',
  },
  {
    id: 'restaurant-sgw-04',
    name: 'Pizza Pizza',
    category: 'restaurant',
    campus: 'SGW',
    latitude: 45.4961,
    longitude: -73.5791,
    address: '1822 Sainte-Catherine St W, Montreal, QC',
  },
  {
    id: 'restaurant-sgw-05',
    name: 'Burger King',
    category: 'restaurant',
    campus: 'SGW',
    latitude: 45.4963,
    longitude: -73.5772,
    address: '2020 Rue Mackay, Montreal, QC',
  },
  {
    id: 'restaurant-sgw-06',
    name: 'A&W',
    category: 'restaurant',
    campus: 'SGW',
    latitude: 45.4978,
    longitude: -73.5759,
    address: '1500 Sainte-Catherine St W, Montreal, QC',
  },
  {
    id: 'restaurant-sgw-07',
    name: 'Copper Branch',
    category: 'restaurant',
    campus: 'SGW',
    latitude: 45.4953,
    longitude: -73.5773,
    address: '1245 Bishop St, Montreal, QC',
  },
  {
    id: 'restaurant-sgw-08',
    name: 'Lola Rosa',
    category: 'restaurant',
    campus: 'SGW',
    latitude: 45.4972,
    longitude: -73.5757,
    address: '545 Milton St, Montreal, QC',
  },
  {
    id: 'restaurant-sgw-09',
    name: 'Kinton Ramen',
    category: 'restaurant',
    campus: 'SGW',
    latitude: 45.4966,
    longitude: -73.5763,
    address: '1436 Bishop St, Montreal, QC',
  },
  {
    id: 'restaurant-sgw-10',
    name: 'Le Warehouse',
    category: 'restaurant',
    campus: 'SGW',
    latitude: 45.4967,
    longitude: -73.5769,
    address: '1446 Crescent St, Montreal, QC',
  },
  {
    id: 'restaurant-sgw-11',
    name: 'Restaurant Basha',
    category: 'restaurant',
    campus: 'SGW',
    latitude: 45.4971,
    longitude: -73.5775,
    address: '2020 Mackay St, Montreal, QC',
  },
  {
    id: 'restaurant-sgw-12',
    name: 'Sammi & Soupe Dumpling',
    category: 'restaurant',
    campus: 'SGW',
    latitude: 45.4957,
    longitude: -73.5765,
    address: '1909 Saint-Mathieu St, Montreal, QC',
  },
  {
    id: 'restaurant-sgw-13',
    name: 'Burritoville',
    category: 'restaurant',
    campus: 'SGW',
    latitude: 45.4959,
    longitude: -73.5786,
    address: '2055 Bishop St, Montreal, QC',
  },
  {
    id: 'restaurant-sgw-14',
    name: 'Mister Steer',
    category: 'restaurant',
    campus: 'SGW',
    latitude: 45.4962,
    longitude: -73.577,
    address: '1191 Rue de la Montagne, Montreal, QC',
  },
  {
    id: 'restaurant-sgw-15',
    name: 'JUN I',
    category: 'restaurant',
    campus: 'SGW',
    latitude: 45.4938,
    longitude: -73.5801,
    address: '156 Avenue Laurier O, Montreal, QC',
  },
  {
    id: 'restaurant-loy-01',
    name: 'Notre-Boeuf-de-Grace',
    category: 'restaurant',
    campus: 'LOYOLA',
    latitude: 45.4619,
    longitude: -73.6384,
    address: '5732 Sherbrooke St W, Montreal, QC',
  },
  {
    id: 'restaurant-loy-02',
    name: 'Villa du Souvlaki',
    category: 'restaurant',
    campus: 'LOYOLA',
    latitude: 45.4608,
    longitude: -73.6402,
    address: '5513 Monkland Ave, Montreal, QC',
  },
  {
    id: 'restaurant-loy-03',
    name: 'Jardin Iwaki',
    category: 'restaurant',
    campus: 'LOYOLA',
    latitude: 45.4611,
    longitude: -73.6374,
    address: '5887 Sherbrooke St W, Montreal, QC',
  },
  {
    id: 'restaurant-loy-04',
    name: 'Quartier Perse',
    category: 'restaurant',
    campus: 'LOYOLA',
    latitude: 45.4601,
    longitude: -73.6394,
    address: '5485 Monkland Ave, Montreal, QC',
  },
  {
    id: 'restaurant-loy-05',
    name: 'Pizzeria Geppetto',
    category: 'restaurant',
    campus: 'LOYOLA',
    latitude: 45.4623,
    longitude: -73.6352,
    address: '2500 Beaconsfield Ave, Montreal, QC',
  },
  {
    id: 'restaurant-loy-06',
    name: 'Marathon Souvlaki',
    category: 'restaurant',
    campus: 'LOYOLA',
    latitude: 45.4615,
    longitude: -73.6368,
    address: '5730 Sherbrooke St W, Montreal, QC',
  },
  {
    id: 'restaurant-loy-07',
    name: 'Benny & Co.',
    category: 'restaurant',
    campus: 'LOYOLA',
    latitude: 45.4594,
    longitude: -73.6421,
    address: '6100 Sherbrooke St W, Montreal, QC',
  },
  {
    id: 'restaurant-loy-08',
    name: 'Restaurant Mamma',
    category: 'restaurant',
    campus: 'LOYOLA',
    latitude: 45.4579,
    longitude: -73.6392,
    address: '4900 Sherbrooke St W, Montreal, QC',
  },
  {
    id: 'restaurant-loy-09',
    name: 'Arahova Souvlaki',
    category: 'restaurant',
    campus: 'LOYOLA',
    latitude: 45.4625,
    longitude: -73.6308,
    address: '5990 Monkland Ave, Montreal, QC',
  },
  {
    id: 'restaurant-loy-10',
    name: 'Souvlaki George',
    category: 'restaurant',
    campus: 'LOYOLA',
    latitude: 45.4583,
    longitude: -73.6379,
    address: '6600 Sherbrooke St W, Montreal, QC',
  },
  {
    id: 'restaurant-loy-11',
    name: 'Thai Express',
    category: 'restaurant',
    campus: 'LOYOLA',
    latitude: 45.4576,
    longitude: -73.6418,
    address: '6801 Chemin de la Cote-Saint-Luc, Montreal, QC',
  },
  {
    id: 'restaurant-loy-12',
    name: 'Deli La Trattoria',
    category: 'restaurant',
    campus: 'LOYOLA',
    latitude: 45.4605,
    longitude: -73.6344,
    address: '6127 Sherbrooke St W, Montreal, QC',
  },
  {
    id: 'restaurant-loy-13',
    name: 'Poke Monster',
    category: 'restaurant',
    campus: 'LOYOLA',
    latitude: 45.4591,
    longitude: -73.6361,
    address: '5849 Sherbrooke St W, Montreal, QC',
  },
  {
    id: 'restaurant-loy-14',
    name: 'Nostos',
    category: 'restaurant',
    campus: 'LOYOLA',
    latitude: 45.4632,
    longitude: -73.6289,
    address: '5357 Avenue du Parc, Montreal, QC',
  },
  {
    id: 'restaurant-loy-15',
    name: 'Dunns Famous NDG',
    category: 'restaurant',
    campus: 'LOYOLA',
    latitude: 45.4588,
    longitude: -73.6458,
    address: '5518 Queen Mary Rd, Montreal, QC',
  },
];
